%% Load Data
disp 'Loading protein-protein-interaciton data...';
load('data/simulated_ppi.mat', 'ppiArray');

disp 'Loading pathway core...';
load('data/pathway.mat', 'pathwayArray');

%% generate simulated gene expression data based on ppiArray and significant genes
disp 'Generating simulated gene expression data...';
gid = unique(ppiArray(:));
sig_ppi = getppisubnet(ppiArray, pathwayArray);
for iUniqueProtein=1:length(gid)
    gconn = union(ppiArray(find(ppiArray(:,1)==gid(iUniqueProtein)),2), ...
        ppiArray(find(ppiArray(:,2)==gid(iUniqueProtein)),1));
    node_degree(iUniqueProtein) = length(gconn);
end
sigGeneIdArray = unique(sig_ppi(:));
for i=1:length(sigGeneIdArray)
    gconn = union(sig_ppi(find(sig_ppi(:,1)==sigGeneIdArray(i)),2), ...
        sig_ppi(find(sig_ppi(:,2)==sigGeneIdArray(i)),1));
    sig_node_degree(i) = length(gconn);
end

[temp,idx_sig] = intersect(gid, sigGeneIdArray);
m = 20; n = 20;

% simulation data could be generated by following code
X0 = zeros(1, length(gid));
X0(idx_sig) = 1;
weight = 20;
[X, geneArray] = simgenesfromppi(ppiArray, X0, m, n, weight);
geneIdArray = unique(ppiArray(:));

logGeneArray = log2(geneArray+4);
c1 = 1:m; c2 = (m+1):(m+n);
geneLabelArray(c1) = 1;
geneLabelArray(c2) = 2;
[H,P] = ttest2(logGeneArray(:,c1)', logGeneArray(:,c2)');
P(P==1) = 0.9999;
P(P<1e-15) = 1e-15;
Zscore = icdf('normal', 1-P, 0, 1);
Zscore = (Zscore-mean(Zscore))/std(Zscore);

% select one of hub gene as the seed gene
idx_hub = find(sig_node_degree > mean(sig_node_degree));
t = Zscore(idx_sig);
[a b] = min(t(idx_hub));
seedGeneIdArray = sigGeneIdArray(idx_hub(b));

%% Save Genes
disp 'Saving simulated gene expression data...';
save('data/simulated_genes_gg.mat', 'geneArray', 'geneIdArray', 'geneLabelArray');
disp 'Saving seed ids...';
save('data/seed_gene_ids.mat', 'seedGeneIdArray');
disp 'Saving significant genes for truth...';
save('data/significant_genes.mat', 'sigGeneIdArray');
disp 'Output files have been written:';
disp '  data/simulated_genes_gg.mat';
disp '  data/seed_gene_ids.mat';
disp '  data/significant_genes.mat';


